//
//  UIColor+Additions.swift
//
//  Generated by Zeplin on 3/24/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {
  class var background: UIColor {
//    EDF0F2
    return UIColor(red: 237.0 / 255.0, green: 240.0 / 255.0, blue: 242.0 / 255.0, alpha: 1.0)
  }

	class var slate50: UIColor {
		return UIColor(red: 58.0 / 255.0, green: 75.0 / 255.0, blue: 91.0 / 255.0, alpha: 0.5)
	}

	class var charcoalGrey: UIColor {
		return UIColor(red: 65.0 / 255.0, green: 76.0 / 255.0, blue: 78.0 / 255.0, alpha: 1.0)
	}

	class var vividPurple: UIColor {
		return UIColor(red: 144.0 / 255.0, green: 18.0 / 255.0, blue: 254.0 / 255.0, alpha: 1.0)
	}

	class var darkishBlue: UIColor {
		return UIColor(red: 0.0, green: 74.0 / 255.0, blue: 148.0 / 255.0, alpha: 1.0)
	}

	class var dodgerBlue: UIColor {
		return UIColor(red: 46.0 / 255.0, green: 144.0 / 255.0, blue: 243.0 / 255.0, alpha: 1.0)
	}

	class var azul: UIColor {
		return UIColor(red: 38.0 / 255.0, green: 121.0 / 255.0, blue: 238.0 / 255.0, alpha: 1.0)
	}

	class var dodgerBlueTwo: UIColor {
		return UIColor(red: 46.0 / 255.0, green: 144.0 / 255.0, blue: 242.0 / 255.0, alpha: 1.0)
	}

	class var silver: UIColor {
		return UIColor(red: 186.0 / 255.0, green: 192.0 / 255.0, blue: 198.0 / 255.0, alpha: 1.0)
	}
}
