//
//  UIFont+Additions.swift
//
//  Generated by Zeplin on 3/24/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIFont {
	class func aliceNameFontFont() -> UIFont? {
		return UIFont(name: "Isidora-Light", size: 64.0)
	}

	class func buttonFontFont() -> UIFont? {
		return UIFont(name: "Trenda-Black", size: 24.0)
	}

	class func headerFontFont() -> UIFont? {
		return UIFont(name: "Trenda-Black", size: 20.0)
	}

	class func recordHelpMessageFont() -> UIFont? {
		return UIFont(name: "Trenda-Black", size: 20.0)
	}

	class func userSpeechResponseFontFont() -> UIFont? {
		return UIFont(name: "Trenda-Black", size: 20.0)
	}

	class func aliceMessageFontFont() -> UIFont? {
		return UIFont(name: "Trenda-Black", size: 20.0)
	}

	class func priceFontFont() -> UIFont? {
		return UIFont(name: "Trenda-Black", size: 20.0)
	}

	class func questionHeaderFontFont() -> UIFont? {
		return UIFont(name: "Trenda-Bold", size: 18.0)
	}

	class func subtitleFontFont() -> UIFont? {
		return UIFont(name: "Trenda-Semibold", size: 14.0)
	}

	class func questionFontFont() -> UIFont? {
		return UIFont(name: "Trenda-Semibold", size: 14.0)
	}

	class func perMonthFontFont() -> UIFont? {
		return UIFont(name: "Trenda-Black", size: 8.0)
	}
}
