//
//  UIFont+Additions.swift
//
//  Generated by Zeplin on 3/24/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIFont {
	class func aliceNameFontFont() -> UIFont? {
		return UIFont(name: "Isidora-Light", size: 64.0)
	}

	class func hiButtonFontFont() -> UIFont? {
		return UIFont(name: "Trenda-Black", size: 24.0)
	}

	class func headerFontFont() -> UIFont? {
		return UIFont(name: "Trenda-Black", size: 20.0)
	}

	class func recordHelpMessageFont() -> UIFont? {
		return UIFont(name: "Trenda-Black", size: 20.0)
	}

	class func subtitleFontFont() -> UIFont? {
		return UIFont(name: "Trenda-Semibold", size: 14.0)
	}
}
